apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/k8-assignment-app/container1/cnt1
          ports:
            - containerPort: 6000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: shared-volume
              mountPath: /Emayan_PV_dir
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: my-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/k8-assignment-app/container2/cnt2
          ports:
            - containerPort: 7000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: shared-volume
              mountPath: /Emayan_PV_dir
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: my-pvc
